[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
swap_program = "37jM1XBNe4MJeN2cfFS6yjx6ybZ5eJMNpTRZWhnAiDna"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/swap-program.ts"

[test]
startup_wait = 20000

[test.validator]
url = "https://api.devnet.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
